const Accordiononedata = [
  {
    cont1: "Counting and Numbers up to 5",
    list1: "Counting up to 5",
    list2: "Counting of objects up to 5",
    list3: "Counting of objects with different colors up to",
    list4: "Counting of objects with different colors up to",
    list5: "Counting of objects with different colors up to",
    list6: "Counting of objects with different colors up to",
    list7: "Counting of objects with different colors up to",
  },
  {
    cont1: "Counting and Numbers up to 9",
    list1: "Counting up to nine",
    list2: "Counting of object up to nine",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
  },
  {
    cont1: "Counting and Numbers up to 18",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
  },
  {
    cont1: "Counting and Numbers up to 20",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
    list8: "Associating letter with object",
  },
  {
    cont1: "time",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
    list8: "Associating letter with object",
  },
  {
    cont1: "2D shapes",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
    list8: "Associating letter with object",
  },
  {
    cont1: "Colors",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    list4: "Associating letter with object",
    list5: "Associating letter with object",
    list6: "Associating letter with object",
    list7: "Associating letter with object",
    list8: "Associating letter with object",
  },
];

export default Accordiononedata;
