const AccordianData = [
  {
    cont1: "Alphabet",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 1,
  },
  {
    cont1: "Noun",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 2,
  },
  {
    cont1: "Adjective",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 3,
  },
  {
    cont1: "Punctuation",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 4,
  },
  {
    cont1: "Prefix and sufix",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 5,
  },
  {
    cont1: "Figure of Speech",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 6,
  },
  {
    cont1: "Pronoun",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 7,
  },
  {
    cont1: "Verb",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 7,
  },
  {
    cont1: "Verb Tense",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 8,
  },
  {
    cont1: "Sentence",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 9,
  },
  {
    cont1: "Vocabulary",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 10,
  },
  {
    cont1: "Finite and None Finite",
    list1: "Alphabet (before and After)",
    list2: "Missing Alphabets",
    list3: "Associating letter with object",
    id: 11,
  },
];

export default AccordianData;
